// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	comment "my-tiktok/cmd/api/biz/router/comment"
	favorite "my-tiktok/cmd/api/biz/router/favorite"
	feed "my-tiktok/cmd/api/biz/router/feed"
	message "my-tiktok/cmd/api/biz/router/message"
	publish "my-tiktok/cmd/api/biz/router/publish"
	relation "my-tiktok/cmd/api/biz/router/relation"
	user "my-tiktok/cmd/api/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	message.Register(r)

	comment.Register(r)

	favorite.Register(r)

	feed.Register(r)

	user.Register(r)

	relation.Register(r)

	publish.Register(r)

}
