// Code generated by hertz generator.

package main

import (
	"context"
	"my-tiktok/biz/dal"
	"my-tiktok/biz/mw/jwt"
	"my-tiktok/biz/mw/minio"
	"my-tiktok/register"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/reverseproxy"
)

// Set up /src/*name route forwarding to access minio from external network
func minioReverseProxy(c context.Context, ctx *app.RequestContext) {
	proxy, _ := reverseproxy.NewSingleHostReverseProxy("http://localhost:9000")
	ctx.URI().SetPath(ctx.Param("name"))
	hlog.CtxInfof(c, string(ctx.Request.URI().Path()))
	proxy.ServeHTTP(c, ctx)
}

func Init() {
	dal.Init()
	jwt.Init()
	minio.Init()
}

func main() {
	Init()
	h := server.Default(
		server.WithStreamBody(true),
		server.WithHostPorts("0.0.0.0:18005"),
	)

	h.GET("/src/*name", minioReverseProxy)
	register.Register(h)

	h.Spin()
}
